export interface DesignCard {
  id: string;
  title: string;
  image: string;
  tag?: string;
  description?: string;
}

export interface DesignCategory {
  slug: string;
  name: string;
  group: string;
  heroTitle: string;
  heroSubtitle: string;
  heroImage: string;
  metaTitle: string;
  metaDescription: string;
  designs: DesignCard[];
}

export const DESIGN_CATEGORIES: DesignCategory[] = [
  {
    slug: "crockery-unit-designs",
    name: "Crockery Unit Designs",
    group: "Dining & Storage",
    heroTitle: "Our Crockery Units Are Designed to Complement Your Interiors",
    heroSubtitle:
      "Transform your dining space with innovative crockery unit designs that bring together elegance, utility, and flawless craftsmanship.",
    heroImage: "/images/design-ideas/crockery-hero.jpg",
    metaTitle: "Crockery Unit Designs | The Bright Space Interiors",
    metaDescription:
      "Explore bespoke crockery unit designs featuring glass display cabinets, ambient illumination, and premium finishes crafted for luxury dining spaces.",
    designs: [
      {
        id: "crockery-1",
        title: "Timeless Elegance in Classic Crockery Unit",
        image: "/images/design-ideas/crockery-1.jpg",
        tag: "Classic Luxury",
        description: "Fluted glass shutters with antique brass handles and soft recessed strip lighting.",
      },
      {
        id: "crockery-2",
        title: "A Touch of Gold Luxury Meets Functionality",
        image: "/images/design-ideas/crockery-2.jpg",
        tag: "Modern Glam",
        description: "Gold trim profiles, tinted tempered glass, and custom velvet-lined silverware pullouts.",
      },
      {
        id: "crockery-3",
        title: "The Royal Display: Opulence in Every Detail",
        image: "/images/design-ideas/crockery-3.jpg",
        tag: "Statement Piece",
        description: "Floor-to-ceiling unit with backlit onyx backdrop and built-in stemware racks.",
      },
      {
        id: "crockery-4",
        title: "Modern Minimalist Crockery Unit",
        image: "/images/design-ideas/crockery-4.jpg",
        tag: "Minimalist",
        description: "Handleless touch-to-open push cabinetry finished in ultra-matte cashmere lacquer.",
      },
      {
        id: "crockery-5",
        title: "Contemporary Glass-Front Display Cabinet",
        image: "/images/design-ideas/crockery-5.jpg",
        tag: "Contemporary",
        description: "Black aluminium-framed tempered glass doors with vertical LED profiles and smoked mirror backing.",
      },
      {
        id: "crockery-6",
        title: "Warm Wooden Crockery Unit with Ambient Lighting",
        image: "/images/design-ideas/crockery-6.jpg",
        tag: "Warm Wood",
        description: "Natural walnut veneer paired with concealed warm 3000K LED illumination for cozy entertaining.",
      },
    ],
  },
  {
    slug: "modular-kitchen-designs",
    name: "Modular Kitchen Designs",
    group: "Kitchen & Dining",
    heroTitle: "Ergonomic Modular Kitchens Engineered for Modern Living",
    heroSubtitle:
      "Experience culinary excellence with custom modular kitchen layouts designed for optimal workflow, premium durability, and bespoke aesthetics.",
    heroImage: "/images/design-ideas/kitchen-hero.jpg",
    metaTitle: "Modular Kitchen Designs | The Bright Space Interiors",
    metaDescription:
      "Discover modern modular kitchen layouts including island, L-shaped, and parallel kitchens with luxury finishes and smart storage.",
    designs: [
      {
        id: "kitchen-1",
        title: "Modern Modular Kitchen",
        image: "/images/design-ideas/kitchen-1.jpg",
        tag: "Modern",
        description: "Clean lines with integrated finger-pull profiles and quartz waterfall countertops.",
      },
      {
        id: "kitchen-2",
        title: "Luxury Island Kitchen",
        image: "/images/design-ideas/kitchen-2.jpg",
        tag: "Luxury",
        description: "Central culinary island with built-in hob, breakfast seating, and suspended pendant lights.",
      },
      {
        id: "kitchen-3",
        title: "Minimalist Kitchen",
        image: "/images/design-ideas/kitchen-3.jpg",
        tag: "Minimalist",
        description: "Seamless matte handleless cabinetry with recessed under-cabinet task lighting.",
      },
      {
        id: "kitchen-4",
        title: "Warm Wooden Kitchen",
        image: "/images/design-ideas/kitchen-4.jpg",
        tag: "Natural Wood",
        description: "Natural oak grain shutters combined with polished porcelain slab backsplash.",
      },
      {
        id: "kitchen-5",
        title: "Contemporary Kitchen",
        image: "/images/design-ideas/kitchen-5.jpg",
        tag: "Contemporary",
        description: "Two-tone cabinetry in charcoal grey and warm sand with soft-close tandem boxes.",
      },
      {
        id: "kitchen-6",
        title: "Parallel Chef's Kitchen",
        image: "/images/design-ideas/kitchen-6.jpg",
        tag: "Chef Grade",
        description: "Dual-counter parallel layout maximizing prep space with built-in pantry tall-units.",
      },
    ],
  },
  {
    slug: "dining-room-designs",
    name: "Dining Room Designs",
    group: "Dining & Storage",
    heroTitle: "Bespoke Dining Spaces That Bring Family and Guests Together",
    heroSubtitle:
      "From intimate family meals to grand celebration banquets, design your dining room with tailored furniture, lighting, and luxurious ambiance.",
    heroImage: "/images/design-ideas/dining-hero.jpg",
    metaTitle: "Dining Room Designs | The Bright Space Interiors",
    metaDescription:
      "Discover luxury dining room interior concepts featuring marble tables, custom chandeliers, and ergonomic seating arrangements.",
    designs: [
      {
        id: "dining-1",
        title: "Elegant Dining Space",
        image: "/images/design-ideas/dining-1.jpg",
        tag: "Classic Elegance",
        description: "Polished Italian marble tabletop complemented by custom upholstered velvet dining chairs.",
      },
      {
        id: "dining-2",
        title: "Modern Dining Interiors",
        image: "/images/design-ideas/dining-2.jpg",
        tag: "Modern Chic",
        description: "Sleek sculptural metal base dining table beneath an artistic linear brass chandelier.",
      },
      {
        id: "dining-3",
        title: "Luxury Dining Area",
        image: "/images/design-ideas/dining-3.jpg",
        tag: "High Luxury",
        description: "Formal dining hall with mirrored accent wall, crystal lighting, and custom buffet credenza.",
      },
      {
        id: "dining-4",
        title: "Minimalist Dining Room",
        image: "/images/design-ideas/dining-4.jpg",
        tag: "Minimalist",
        description: "Clean organic solid wood dining ensemble centered under minimalist ceramic pendant cones.",
      },
      {
        id: "dining-5",
        title: "Scandinavian Dining Suite",
        image: "/images/design-ideas/dining-5.jpg",
        tag: "Nordic",
        description: "Light oak textures, curved wishbone seating, and ample natural window light.",
      },
      {
        id: "dining-6",
        title: "Grand Marble Dining Hall",
        image: "/images/design-ideas/dining-6.jpg",
        tag: "Grand Scale",
        description: "Ten-seater dining centerpiece with fluted wall panels and architectural cove illumination.",
      },
    ],
  },
  {
    slug: "master-bedroom-designs",
    name: "Master Bedroom Designs",
    group: "Bedrooms & Suites",
    heroTitle: "Sanctuaries of Serenity and Bespoke Comfort",
    heroSubtitle:
      "Retreat into a master bedroom tailored to your lifestyle, incorporating luxury panelling, customized headboards, and soothing ambient lighting.",
    heroImage: "/images/design-ideas/bedroom-hero.jpg",
    metaTitle: "Master Bedroom Designs | The Bright Space Interiors",
    metaDescription:
      "Explore peaceful master bedroom design ideas with bespoke headboards, integrated wardrobes, and ambient accent lighting.",
    designs: [
      {
        id: "bedroom-1",
        title: "Luxury Master Suite",
        image: "/images/design-ideas/bedroom-1.jpg",
        tag: "Luxury",
        description: "Floor-to-ceiling upholstered velvet headboard wall with integrated brass pendant drops.",
      },
      {
        id: "bedroom-2",
        title: "Modern Minimalist Bedroom",
        image: "/images/design-ideas/bedroom-2.jpg",
        tag: "Minimalist",
        description: "Low-profile floating platform bed flanked by floating bedside tables and concealed cove LEDs.",
      },
      {
        id: "bedroom-3",
        title: "Warm Neutral Bedroom",
        image: "/images/design-ideas/bedroom-3.jpg",
        tag: "Warm Neutral",
        description: "Layered linen textiles, fluted timber acoustic accent panels, and soft warm lighting.",
      },
      {
        id: "bedroom-4",
        title: "Contemporary Bedroom",
        image: "/images/design-ideas/bedroom-4.jpg",
        tag: "Contemporary",
        description: "Geometric veneer wall treatment with integrated wireless bedside charging and reading sconces.",
      },
      {
        id: "bedroom-5",
        title: "Royal Velvet Headboard Suite",
        image: "/images/design-ideas/bedroom-5.jpg",
        tag: "Bespoke",
        description: "Tufted wingback headboard paired with a plush lounge chaise and rich hardwood flooring.",
      },
      {
        id: "bedroom-6",
        title: "Bohemian Chic Master Retreat",
        image: "/images/design-ideas/bedroom-6.jpg",
        tag: "Organic Chic",
        description: "Cane and rattan headboard accents with breathable organic fabrics and tranquil ambient tones.",
      },
    ],
  },
  {
    slug: "false-ceiling-designs",
    name: "False Ceiling Designs",
    group: "Architectural Elements",
    heroTitle: "Architectural Ceiling Treatments with Integrated Illumination",
    heroSubtitle:
      "Elevate your home's interior volume with layered gypsum ceilings, perimeter cove lighting, and artistic wooden rafter details.",
    heroImage: "/images/design-ideas/ceiling-hero.jpg",
    metaTitle: "False Ceiling Designs | The Bright Space Interiors",
    metaDescription:
      "Discover modern false ceiling ideas featuring cove lighting, gypsum tiers, wooden rafters, and magnetic track lights.",
    designs: [
      {
        id: "ceiling-1",
        title: "Modern Cove Lighting",
        image: "/images/design-ideas/ceiling-1.jpg",
        tag: "Ambient Glow",
        description: "Perimeter indirect cove lighting casting a warm uniform glow across the ceiling plane.",
      },
      {
        id: "ceiling-2",
        title: "Luxury Gypsum Ceiling",
        image: "/images/design-ideas/ceiling-2.jpg",
        tag: "Multi-Tier",
        description: "Recessed multi-tiered gypsum tray ceiling with dimmable architectural spot arrays.",
      },
      {
        id: "ceiling-3",
        title: "Minimalist Ceiling",
        image: "/images/design-ideas/ceiling-3.jpg",
        tag: "Minimalist",
        description: "Flush ceiling with recessed magnetic track lights and shadow-line wall gaps.",
      },
      {
        id: "ceiling-4",
        title: "Decorative Ceiling Design",
        image: "/images/design-ideas/ceiling-4.jpg",
        tag: "Artistic",
        description: "Laser-cut jaali insert panels backlit with diffused warm LED sheets for divine ambiance.",
      },
      {
        id: "ceiling-5",
        title: "Wooden Rafter Ceiling Concept",
        image: "/images/design-ideas/ceiling-5.jpg",
        tag: "Timber Accent",
        description: "Parallel natural oak wood rafters adding warmth, depth, and linear visual rhythm.",
      },
      {
        id: "ceiling-6",
        title: "Geometric Floating Island Ceiling",
        image: "/images/design-ideas/ceiling-6.jpg",
        tag: "Contemporary",
        description: "Suspended floating island ceiling element with soft halo edge illumination.",
      },
    ],
  },
  {
    slug: "wardrobe-designs",
    name: "Wardrobe Designs",
    group: "Bedrooms & Suites",
    heroTitle: "Tailored Wardrobe Systems for Effortless Organization",
    heroSubtitle:
      "Custom storage solutions blending luxury finishes, intuitive organization, and space-saving mechanisms for your daily routine.",
    heroImage: "/images/design-ideas/wardrobe-hero.jpg",
    metaTitle: "Wardrobe Designs | The Bright Space Interiors",
    metaDescription:
      "Explore custom wardrobe designs including sliding doors, walk-in closets, tinted glass shutters, and sensor-lit accessories.",
    designs: [
      {
        id: "wardrobe-1",
        title: "Sliding Wardrobe",
        image: "/images/design-ideas/wardrobe-1.jpg",
        tag: "Space Saving",
        description: "Smooth glide floor-to-ceiling sliding panels finished with acoustic fabric and bronze metal trim.",
      },
      {
        id: "wardrobe-2",
        title: "Walk-In Wardrobe",
        image: "/images/design-ideas/wardrobe-2.jpg",
        tag: "Walk-In Closet",
        description: "Dedicated dressing sanctuary with glass display cases, sensor-lit shelves, and central island.",
      },
      {
        id: "wardrobe-3",
        title: "Glass-Front Wardrobe",
        image: "/images/design-ideas/wardrobe-3.jpg",
        tag: "Boutique Style",
        description: "Smoked reflective glass doors revealing warm illuminated shelving for boutique luxury.",
      },
      {
        id: "wardrobe-4",
        title: "Space-Saving Wardrobe",
        image: "/images/design-ideas/wardrobe-4.jpg",
        tag: "Compact",
        description: "Integrated study-table-and-wardrobe combination ideal for compact modern urban apartments.",
      },
      {
        id: "wardrobe-5",
        title: "Floor-to-Ceiling Built-In Wardrobe",
        image: "/images/design-ideas/wardrobe-5.jpg",
        tag: "Seamless",
        description: "Handleless flush hinged doors painted to match bedroom walls for an uninterrupted look.",
      },
      {
        id: "wardrobe-6",
        title: "Illuminated Boutique Closet",
        image: "/images/design-ideas/wardrobe-6.jpg",
        tag: "Illuminated",
        description: "Concealed micro-LED profiles embedded into hanger rods and shoe display drawers.",
      },
    ],
  },
  {
    slug: "living-room-designs",
    name: "Living Room Designs",
    group: "Living & Lounge",
    heroTitle: "Signature Living Rooms Designed to Impress and Comfort",
    heroSubtitle:
      "Create an unforgettable first impression with inviting conversation layouts, custom entertainment walls, and premium bespoke furniture.",
    heroImage: "/images/design-ideas/living-hero.jpg",
    metaTitle: "Living Room Designs | The Bright Space Interiors",
    metaDescription:
      "Discover inspiring living room designs crafted with luxury furniture layouts, accent walls, and balanced lighting schemes.",
    designs: [
      {
        id: "living-1",
        title: "Contemporary Living Room",
        image: "/images/design-ideas/living-1.jpg",
        tag: "Contemporary",
        description: "Low-slung modular sofa anchored by an oversized wool rug and organic coffee table ensemble.",
      },
      {
        id: "living-2",
        title: "Luxury Lounge",
        image: "/images/design-ideas/living-2.jpg",
        tag: "High Luxury",
        description: "Book-matched Italian marble feature wall flanked by bronze sconces and velvet lounge armchairs.",
      },
      {
        id: "living-3",
        title: "Minimalist Living Space",
        image: "/images/design-ideas/living-3.jpg",
        tag: "Minimalist",
        description: "Decluttered aesthetics focusing on pure architectural light, clean forms, and subtle textures.",
      },
      {
        id: "living-4",
        title: "Warm Neutral Interiors",
        image: "/images/design-ideas/living-4.jpg",
        tag: "Warm Neutral",
        description: "Calming palette of taupe, beige, and warm oak bringing relaxed luxury to daily family life.",
      },
      {
        id: "living-5",
        title: "Grand Double-Height Living Room",
        image: "/images/design-ideas/living-5.jpg",
        tag: "Grand Volume",
        description: "Dramatic double-height windows draped in sheer linen with a cascading multi-tier chandelier.",
      },
      {
        id: "living-6",
        title: "Mid-Century Modern Living Hall",
        image: "/images/design-ideas/living-6.jpg",
        tag: "Mid-Century",
        description: "Tapered wooden legs, warm leather lounge chairs, and rich sculptural brass accessories.",
      },
    ],
  },
  {
    slug: "bathroom-designs",
    name: "Bathroom Designs",
    group: "Baths & Wellness",
    heroTitle: "Spa-Inspired Bathrooms Tailored for Everyday Rejuvenation",
    heroSubtitle:
      "Transform functional bathrooms into serene wellness havens with marble finishes, backlit floating vanities, and walk-in rain showers.",
    heroImage: "/images/design-ideas/bathroom-hero.jpg",
    metaTitle: "Bathroom Designs | The Bright Space Interiors",
    metaDescription:
      "Explore modern luxury bathroom designs with floating vanities, frameless glass shower enclosures, and designer tiles.",
    designs: [
      {
        id: "bathroom-1",
        title: "Luxury Marble Bathroom",
        image: "/images/design-ideas/bathroom-1.jpg",
        tag: "Marble Suite",
        description: "Floor-to-ceiling large format marble slabs with concealed wall-hung fixtures and gold trims.",
      },
      {
        id: "bathroom-2",
        title: "Modern Vanity",
        image: "/images/design-ideas/bathroom-2.jpg",
        tag: "Floating Vanity",
        description: "Floating quartz countertop vanity with undermount basin and halo-backlit circular mirror.",
      },
      {
        id: "bathroom-3",
        title: "Minimalist Bathroom",
        image: "/images/design-ideas/bathroom-3.jpg",
        tag: "Minimalist",
        description: "Matte black tapware paired with micro-cement walls and concealed linear trench drains.",
      },
      {
        id: "bathroom-4",
        title: "Spa-Inspired Bathroom",
        image: "/images/design-ideas/bathroom-4.jpg",
        tag: "Spa Haven",
        description: "Freestanding soaking tub beside a floor-to-ceiling glass wall overlooking a private greenery court.",
      },
      {
        id: "bathroom-5",
        title: "Frameless Glass Shower Suite",
        image: "/images/design-ideas/bathroom-5.jpg",
        tag: "Walk-In Shower",
        description: "Walk-in wet room shower with recessed thermostatic ceiling-mounted rainfall fixture.",
      },
      {
        id: "bathroom-6",
        title: "Monochromatic Powder Room",
        image: "/images/design-ideas/bathroom-6.jpg",
        tag: "Powder Room",
        description: "Dramatic fluted pedestal basin with dark textured wallpaper and warm spotlight beam.",
      },
    ],
  },
  {
    slug: "balcony-designs",
    name: "Balcony Designs",
    group: "Outdoor & Extended",
    heroTitle: "Bespoke Balconies and Outdoor Retreats",
    heroSubtitle:
      "Transform compact urban balconies and sprawling terraces into verdant, relaxing open-air living extensions of your home.",
    heroImage: "/images/design-ideas/balcony-hero.jpg",
    metaTitle: "Balcony Designs | The Bright Space Interiors",
    metaDescription:
      "Discover creative balcony design ideas featuring vertical gardens, artificial turf, weatherproof seating, and cozy lighting.",
    designs: [
      {
        id: "balcony-1",
        title: "Cozy Balcony",
        image: "/images/design-ideas/balcony-1.jpg",
        tag: "Cozy Corner",
        description: "Comfortable weather-resistant egg swing chair surrounded by potted greenery and fairy festoons.",
      },
      {
        id: "balcony-2",
        title: "Modern Balcony Seating",
        image: "/images/design-ideas/balcony-2.jpg",
        tag: "Urban Lounge",
        description: "Custom bench seating with water-resistant cushions and integrated hidden storage underneath.",
      },
      {
        id: "balcony-3",
        title: "Green Balcony",
        image: "/images/design-ideas/balcony-3.jpg",
        tag: "Vertical Garden",
        description: "Full vertical green wall featuring automated micro-drip irrigation and lush foliage.",
      },
      {
        id: "balcony-4",
        title: "Compact Balcony Makeover",
        image: "/images/design-ideas/balcony-4.jpg",
        tag: "Compact",
        description: "Foldable railing-mounted bistro table and folding chairs maximizing every square foot.",
      },
      {
        id: "balcony-5",
        title: "Wooden Deck Sunset Lounge",
        image: "/images/design-ideas/balcony-5.jpg",
        tag: "Deck Flooring",
        description: "Interlocking composite teak wood deck tiles illuminated by low-glare step accent lights.",
      },
      {
        id: "balcony-6",
        title: "Vertical Garden Balcony Retreat",
        image: "/images/design-ideas/balcony-6.jpg",
        tag: "Zen Retreat",
        description: "Pebble stone border, Buddha water cascade, and natural bamboo privacy screening.",
      },
    ],
  },
  {
    slug: "cafe-interiors",
    name: "Cafe Interiors",
    group: "Commercial & Hospitality",
    heroTitle: "Captivating Cafe & Coffee Lounge Environments",
    heroSubtitle:
      "Design atmospheric hospitality spaces that attract coffee lovers, optimize table turns, and establish a memorable visual identity.",
    heroImage: "/images/design-ideas/cafe-hero.jpg",
    metaTitle: "Cafe Interior Designs | The Bright Space Interiors",
    metaDescription:
      "Explore trendy cafe interior concepts including rustic coffee bars, industrial aesthetics, and instagrammable dining nooks.",
    designs: [
      {
        id: "cafe-1",
        title: "Modern Cafe",
        image: "/images/design-ideas/cafe-1.jpg",
        tag: "Modern Urban",
        description: "Terrazzo counter with fluted wood base and ambient linear lighting above the barista station.",
      },
      {
        id: "cafe-2",
        title: "Luxury Coffee Lounge",
        image: "/images/design-ideas/cafe-2.jpg",
        tag: "Lounge Concept",
        description: "Plush leather banquette seating, dark walnut tables, and warm vintage brass lighting accents.",
      },
      {
        id: "cafe-3",
        title: "Minimalist Cafe",
        image: "/images/design-ideas/cafe-3.jpg",
        tag: "Minimalist",
        description: "Nordic light wood elements, whitewashed brick surfaces, and generous natural sunlight.",
      },
      {
        id: "cafe-4",
        title: "Cozy Cafe Interiors",
        image: "/images/design-ideas/cafe-4.jpg",
        tag: "Cozy & Intimate",
        description: "Intimate bookshelf nooks with warm amber lamps and bespoke upholstered armchairs.",
      },
      {
        id: "cafe-5",
        title: "Rustic Brick Artisan Cafe",
        image: "/images/design-ideas/cafe-5.jpg",
        tag: "Artisan",
        description: "Exposed clay brick masonry combined with industrial matte black piping and chalk menu boards.",
      },
      {
        id: "cafe-6",
        title: "Industrial Chic Coffee Roastery",
        image: "/images/design-ideas/cafe-6.jpg",
        tag: "Industrial",
        description: "Polished concrete floor, visible ductwork, and oversized industrial steel window casements.",
      },
    ],
  },
  {
    slug: "salon-interiors",
    name: "Salon Interiors",
    group: "Commercial & Hospitality",
    heroTitle: "Glamorous Salon and Spa Spaces That Captivate Clients",
    heroSubtitle:
      "Create high-end beauty destinations with ergonomic styling stations, flattering shadowless illumination, and luxurious waiting lounges.",
    heroImage: "/images/design-ideas/salon-hero.jpg",
    metaTitle: "Salon Interior Designs | The Bright Space Interiors",
    metaDescription:
      "Discover salon interior designs with arched mirrors, luxury waiting lounges, pedispa suites, and shadowless lighting.",
    designs: [
      {
        id: "salon-1",
        title: "Luxury Salon",
        image: "/images/design-ideas/salon-1.jpg",
        tag: "Royal Luxury",
        description: "Arched gold-framed full-length mirrors with halo LED illumination and cognac leather styling chairs.",
      },
      {
        id: "salon-2",
        title: "Modern Hair Studio",
        image: "/images/design-ideas/salon-2.jpg",
        tag: "Modern Studio",
        description: "High-contrast monochrome workstations with integrated concealed cable and product management.",
      },
      {
        id: "salon-3",
        title: "Premium Beauty Lounge",
        image: "/images/design-ideas/salon-3.jpg",
        tag: "VIP Lounge",
        description: "Private treatment suites featuring acoustic wall upholstery and soft diffused cove lighting.",
      },
      {
        id: "salon-4",
        title: "Contemporary Salon",
        image: "/images/design-ideas/salon-4.jpg",
        tag: "Contemporary",
        description: "Seamless open floor layout with fluted marble reception counter and gold chandelier centerpiece.",
      },
      {
        id: "salon-5",
        title: "Royal Gilded Styling Stations",
        image: "/images/design-ideas/salon-5.jpg",
        tag: "Classical Glam",
        description: "Intricate Baroque gilded mirror borders paired with imported Italian hydraulic wash stations.",
      },
      {
        id: "salon-6",
        title: "Organic Wellness Spa Lounge",
        image: "/images/design-ideas/salon-6.jpg",
        tag: "Spa Sanctuary",
        description: "Natural bamboo screens, indoor cascading fountain, and soft warm earthen color tones.",
      },
    ],
  },
  {
    slug: "office-interiors",
    name: "Office Interiors",
    group: "Commercial & Hospitality",
    heroTitle: "Productive, Inspiring Workspaces for High-Performance Teams",
    heroSubtitle:
      "Design flexible, collaborative office environments that strengthen corporate culture, empower focused work, and impress visiting clients.",
    heroImage: "/images/design-ideas/office-hero.jpg",
    metaTitle: "Office Interior Designs | The Bright Space Interiors",
    metaDescription:
      "Explore executive office designs, collaborative workstation layouts, high-tech boardrooms, and modern reception lobbies.",
    designs: [
      {
        id: "office-1",
        title: "Modern Corporate Headquarters",
        image: "/images/design-ideas/office-1.jpg",
        tag: "Corporate HQ",
        description: "Sleek reception rotunda with backlit brand emblem and curved architectural wood slat wall.",
      },
      {
        id: "office-2",
        title: "Executive Director Cabin",
        image: "/images/design-ideas/office-2.jpg",
        tag: "Executive Suite",
        description: "Custom leather desk with fluted credenza, private meeting corner, and expansive panoramic views.",
      },
      {
        id: "office-3",
        title: "Collaborative Agile Workspace",
        image: "/images/design-ideas/office-3.jpg",
        tag: "Agile Teams",
        description: "Open workstation benching with sound-dampening acoustic felt baffles and vibrant breakout pods.",
      },
      {
        id: "office-4",
        title: "Ergonomic Open Office Floor",
        image: "/images/design-ideas/office-4.jpg",
        tag: "Ergonomic",
        description: "Height-adjustable sit-to-stand desks equipped with integrated cable trays and task lights.",
      },
      {
        id: "office-5",
        title: "High-Tech Boardroom Suite",
        image: "/images/design-ideas/office-5.jpg",
        tag: "Boardroom",
        description: "Twelve-person marble conference table with integrated pop-up AV connectivity and smart glass privacy.",
      },
      {
        id: "office-6",
        title: "Creative Agency Studio",
        image: "/images/design-ideas/office-6.jpg",
        tag: "Creative Studio",
        description: "Exposed ceilings, writeable whiteboard walls, and relaxed informal beanbag brainstorming zones.",
      },
    ],
  },
  {
    slug: "hotel-interiors",
    name: "Hotel Interiors",
    group: "Commercial & Hospitality",
    heroTitle: "Luxury Hospitality Spaces That Deliver Unforgettable Stays",
    heroSubtitle:
      "From striking lobby atriums to serene guestroom suites, craft world-class hospitality interiors that inspire return visits.",
    heroImage: "/images/design-ideas/hotel-hero.jpg",
    metaTitle: "Hotel Interior Designs | The Bright Space Interiors",
    metaDescription:
      "Discover luxury hotel interior concepts for grand lobbies, executive suites, guestrooms, and fine dining lounges.",
    designs: [
      {
        id: "hotel-1",
        title: "Luxury Hotel Lobby & Lounge",
        image: "/images/design-ideas/hotel-1.jpg",
        tag: "Grand Lobby",
        description: "Monumental central chandelier suspended over book-matched marble floors and plush seating alcoves.",
      },
      {
        id: "hotel-2",
        title: "Executive Hospitality Suite",
        image: "/images/design-ideas/hotel-2.jpg",
        tag: "Suite Luxury",
        description: "Spacious master guestroom with separate living parlor, walk-in dressing, and bespoke wet bar.",
      },
      {
        id: "hotel-3",
        title: "Boutique Hotel Reception",
        image: "/images/design-ideas/hotel-3.jpg",
        tag: "Boutique",
        description: "Intimate brass and fluted terrazzo check-in pods creating an exclusive residential arrival feel.",
      },
      {
        id: "hotel-4",
        title: "Grand Presidential Suite",
        image: "/images/design-ideas/hotel-4.jpg",
        tag: "Presidential",
        description: "Opulent penthouse suite with dedicated dining for eight, private terrace, and Italian bath sanctuary.",
      },
      {
        id: "hotel-5",
        title: "Contemporary Hotel Guestroom",
        image: "/images/design-ideas/hotel-5.jpg",
        tag: "Guest Room",
        description: "Ergonomic hospitality design featuring integrated luggage bench, desk, and master bedside controls.",
      },
      {
        id: "hotel-6",
        title: "Fine Dining Hotel Restaurant",
        image: "/images/design-ideas/hotel-6.jpg",
        tag: "Restaurant",
        description: "Subtly illuminated tables with acoustic ceiling baffles and dramatic sculptural wine display cellar.",
      },
    ],
  },
  {
    slug: "school-interiors",
    name: "School Interiors",
    group: "Commercial & Specialized",
    heroTitle: "Modern Learning Environments That Inspire Curiosity",
    heroSubtitle:
      "Create vibrant, safe, and collaborative educational spaces that foster creativity, engagement, and student well-being.",
    heroImage: "/images/design-ideas/school-hero.jpg",
    metaTitle: "School & Educational Interiors | The Bright Space Interiors",
    metaDescription:
      "Explore modern educational interiors for schools, classrooms, libraries, and science labs designed for active learning.",
    designs: [
      {
        id: "school-1",
        title: "Modern Learning Commons",
        image: "/images/design-ideas/school-1.jpg",
        tag: "Learning Commons",
        description: "Flexible tiered stepped seating with integrated power points for group presentations and reading.",
      },
      {
        id: "school-2",
        title: "Inspiring Kindergarten Classroom",
        image: "/images/design-ideas/school-2.jpg",
        tag: "Early Learning",
        description: "Rounded child-safe furniture, natural timber cubbies, and playful colorful activity zones.",
      },
      {
        id: "school-3",
        title: "High-Tech Digital Science Lab",
        image: "/images/design-ideas/school-3.jpg",
        tag: "STEM Lab",
        description: "Chemical-resistant epoxy worktables with overhead utility raceways and interactive digital screens.",
      },
      {
        id: "school-4",
        title: "Creative Arts & Crafts Studio",
        image: "/images/design-ideas/school-4.jpg",
        tag: "Art Studio",
        description: "Easy-clean polished epoxy flooring, mobile drying racks, and sunlit northern skylights.",
      },
      {
        id: "school-5",
        title: "Ergonomic School Library",
        image: "/images/design-ideas/school-5.jpg",
        tag: "Modern Library",
        description: "Acoustically treated reading alcoves with colorful curved book storage islands and study carrels.",
      },
      {
        id: "school-6",
        title: "Vibrant Student Cafeteria",
        image: "/images/design-ideas/school-6.jpg",
        tag: "Dining Hall",
        description: "Durable bench seating arrangements, bright acoustic panels, and hygienic self-service counters.",
      },
    ],
  },
  {
    slug: "hospital-interiors",
    name: "Hospital Interiors",
    group: "Commercial & Specialized",
    heroTitle: "Healing Healthcare Spaces Combining Hygiene and Compassion",
    heroSubtitle:
      "Design medical clinics and hospital spaces prioritizing patient comfort, clinical hygiene, and seamless caregiver efficiency.",
    heroImage: "/images/design-ideas/hospital-hero.jpg",
    metaTitle: "Hospital & Healthcare Interiors | The Bright Space Interiors",
    metaDescription:
      "Discover patient-centric healthcare interior designs for hospital lobbies, recovery suites, clinics, and consultation rooms.",
    designs: [
      {
        id: "hospital-1",
        title: "Calming Medical Clinic Reception",
        image: "/images/design-ideas/hospital-1.jpg",
        tag: "Clinic Reception",
        description: "Soothing natural wood tones and biophilic greenery creating an anxiety-reducing welcome lounge.",
      },
      {
        id: "hospital-2",
        title: "Premium Patient Recovery Suite",
        image: "/images/design-ideas/hospital-2.jpg",
        tag: "Private Suite",
        description: "Hospitality-grade private patient room with discreet medical headwall, companion sofa-bed, and en-suite bath.",
      },
      {
        id: "hospital-3",
        title: "Pediatric Care Waiting Lounge",
        image: "/images/design-ideas/hospital-3.jpg",
        tag: "Pediatric Care",
        description: "Gentle pastel murals, interactive play modules, and antibacterial seamless vinyl flooring.",
      },
      {
        id: "hospital-4",
        title: "Modern Diagnostic Consultation Room",
        image: "/images/design-ideas/hospital-4.jpg",
        tag: "Consultation",
        description: "Ergonomic doctor desk, wall-mounted digital imaging monitors, and hygienic curtain screening.",
      },
      {
        id: "hospital-5",
        title: "Ergonomic Doctors' Station",
        image: "/images/design-ideas/hospital-5.jpg",
        tag: "Staff Station",
        description: "Centralized nurse communication station with clear lines of sight and acoustic privacy partitions.",
      },
      {
        id: "hospital-6",
        title: "Holistic Wellness Treatment Wing",
        image: "/images/design-ideas/hospital-6.jpg",
        tag: "Wellness Wing",
        description: "Soft indirect lighting, tranquil soundproofing, and seamless anti-microbial wall cladding.",
      },
    ],
  },
  {
    slug: "gym-interiors",
    name: "Gym Interiors",
    group: "Commercial & Specialized",
    heroTitle: "Dynamic Fitness Studios and High-Energy Gym Spaces",
    heroSubtitle:
      "Energize workouts with state-of-the-art gym interiors featuring shock-absorbing rubber floors, bold LED accents, and high-impact zoning.",
    heroImage: "/images/design-ideas/gym-hero.jpg",
    metaTitle: "Gym & Fitness Studio Interiors | The Bright Space Interiors",
    metaDescription:
      "Explore fitness interior designs with high-impact LED lighting, rubber flooring, cardio zones, and boutique yoga studios.",
    designs: [
      {
        id: "gym-1",
        title: "Luxury Fitness Club Floor",
        image: "/images/design-ideas/gym-1.jpg",
        tag: "Fitness Club",
        description: "Spacious layout with industrial exposed ceilings, linear neon accents, and heavy-duty rubber tiles.",
      },
      {
        id: "gym-2",
        title: "Dynamic CrossFit Training Zone",
        image: "/images/design-ideas/gym-2.jpg",
        tag: "CrossFit Box",
        description: "Open turf sprint lane, wall-mounted rig stations, and rugged impact-proof finishes.",
      },
      {
        id: "gym-3",
        title: "Zen Yoga & Pilates Sanctuary",
        image: "/images/design-ideas/gym-3.jpg",
        tag: "Mind & Body",
        description: "Light bamboo timber flooring, full mirrored wall with dimmable perimeter warm cove lighting.",
      },
      {
        id: "gym-4",
        title: "Modern Cardio Studio with LED Accents",
        image: "/images/design-ideas/gym-4.jpg",
        tag: "Cardio Studio",
        description: "Treadmill and cycle rows facing high-definition media walls with energetic RGB light tunnels.",
      },
      {
        id: "gym-5",
        title: "Premium Locker & Steam Lounge",
        image: "/images/design-ideas/gym-5.jpg",
        tag: "Locker Lounge",
        description: "Keyless electronic wooden lockers, vanity grooming counters, and private sauna facilities.",
      },
      {
        id: "gym-6",
        title: "Private Personal Training Studio",
        image: "/images/design-ideas/gym-6.jpg",
        tag: "Personal Training",
        description: "Dedicated VIP coaching suite equipped with functional fitness mirrors and acoustic insulation.",
      },
    ],
  },
  {
    slug: "home-wallpaper",
    name: "Home Wallpaper",
    group: "Finishes & Decor",
    heroTitle: "Curated Designer Wallpapers That Define Character",
    heroSubtitle:
      "Add immediate personality, depth, and tactile luxury to any room with custom wall murals, textured coverings, and metallic prints.",
    heroImage: "/images/design-ideas/wallpaper-hero.jpg",
    metaTitle: "Home Wallpaper Designs | The Bright Space Interiors",
    metaDescription:
      "Discover designer wallpaper styles including metallic textures, botanical murals, geometric prints, and luxury heritage damasks.",
    designs: [
      {
        id: "wallpaper-1",
        title: "Textured Metallic Accent Wallpaper",
        image: "/images/design-ideas/wallpaper-1.jpg",
        tag: "Metallic Texture",
        description: "Subtle gold and bronze leaf shimmer reflecting soft evening lamplight across the master suite.",
      },
      {
        id: "wallpaper-2",
        title: "Botanical Flora & Palm Wall Mural",
        image: "/images/design-ideas/wallpaper-2.jpg",
        tag: "Biophilic Mural",
        description: "Large-scale tropical palm frond mural in muted emerald and sage for a refreshing living room backdrop.",
      },
      {
        id: "wallpaper-3",
        title: "Geometric Minimalist Wallpaper",
        image: "/images/design-ideas/wallpaper-3.jpg",
        tag: "Geometric",
        description: "Fine line-art interlocking diamonds creating visual architectural rhythm in a study room.",
      },
      {
        id: "wallpaper-4",
        title: "Luxury Damask Heritage Wall Covering",
        image: "/images/design-ideas/wallpaper-4.jpg",
        tag: "Heritage",
        description: "Embossed velvet flock damask pattern providing aristocratic grandeur in formal dining halls.",
      },
      {
        id: "wallpaper-5",
        title: "Abstract Watercolor Feature Wall",
        image: "/images/design-ideas/wallpaper-5.jpg",
        tag: "Abstract Art",
        description: "Blended indigo and blush watercolor wash adding artistic depth behind the bed headboard.",
      },
      {
        id: "wallpaper-6",
        title: "Subtle Linen Textured Wallpaper",
        image: "/images/design-ideas/wallpaper-6.jpg",
        tag: "Textured Neutral",
        description: "Organic Belgian linen weave surface adding tactile richness while preserving quiet minimalist calm.",
      },
    ],
  },
  {
    slug: "home-bar",
    name: "Home Bar",
    group: "Dining & Storage",
    heroTitle: "Sophisticated Home Bars for Seamless Entertaining",
    heroSubtitle:
      "Design an exclusive cocktail lounge in your home with backlit bottle displays, custom wine storage, and plush bar seating.",
    heroImage: "/images/design-ideas/bar-hero.jpg",
    metaTitle: "Home Bar Designs | The Bright Space Interiors",
    metaDescription:
      "Explore bespoke home bar designs with backlit onyx counters, climate-controlled wine cellars, and speakeasy lounges.",
    designs: [
      {
        id: "bar-1",
        title: "Luxury Backlit Onyx Home Bar",
        image: "/images/design-ideas/bar-1.jpg",
        tag: "Backlit Onyx",
        description: "Translucent golden onyx counter illuminated from within paired with brushed brass bar stools.",
      },
      {
        id: "bar-2",
        title: "Compact Under-Stairs Speakeasy",
        image: "/images/design-ideas/bar-2.jpg",
        tag: "Space Maximizer",
        description: "Clever utilization of under-stair alcove transformed into a mood-lit cocktail cabinet and sink.",
      },
      {
        id: "bar-3",
        title: "Modern Fluted Wood Cocktail Station",
        image: "/images/design-ideas/bar-3.jpg",
        tag: "Contemporary",
        description: "Curved tambour wood bar counter with black marble top and brass stemware hanging racks.",
      },
      {
        id: "bar-4",
        title: "Contemporary Glass Wine Cellar",
        image: "/images/design-ideas/bar-4.jpg",
        tag: "Wine Display",
        description: "Temperature-controlled glass enclosed wine wall serving as an architectural feature in the dining room.",
      },
      {
        id: "bar-5",
        title: "Rustic Industrial Bar Counter",
        image: "/images/design-ideas/bar-5.jpg",
        tag: "Industrial",
        description: "Reclaimed timber counter supported by blackened steel framing with vintage Edison bulb canopy.",
      },
      {
        id: "bar-6",
        title: "Elegant Brass & Marble Drinks Bar",
        image: "/images/design-ideas/bar-6.jpg",
        tag: "Art Deco",
        description: "Sleek brass shelving suspended from the ceiling above a polished Nero Marquina marble counter.",
      },
    ],
  },
  {
    slug: "pooja-room",
    name: "Pooja Room",
    group: "Spiritual & Traditional",
    heroTitle: "Serene Pooja Units Crafted with Devotion and Sacred Beauty",
    heroSubtitle:
      "Create a tranquil sacred sanctuary at home with intricate jaali work, warm brass bells, backlighting, and pure marble craftsmanship.",
    heroImage: "/images/design-ideas/pooja-hero.jpg",
    metaTitle: "Pooja Room Designs | The Bright Space Interiors",
    metaDescription:
      "Discover serene pooja mandir designs with marble carving, CNC jaali backlights, teakwood frames, and brass accents.",
    designs: [
      {
        id: "pooja-1",
        title: "Traditional Carved Teak Mandir",
        image: "/images/design-ideas/pooja-1.jpg",
        tag: "Traditional",
        description: "Solid Burma teakwood shrine with hand-carved pillars, shikhara dome, and bell hangings.",
      },
      {
        id: "pooja-2",
        title: "Backlit Corian Laser-Cut Pooja Mandap",
        image: "/images/design-ideas/pooja-2.jpg",
        tag: "Modern Corian",
        description: "Seamless white Corian back wall laser-engraved with Gayatri mantra and radiant golden backlighting.",
      },
      {
        id: "pooja-3",
        title: "Modern Minimalist Marble Temple",
        image: "/images/design-ideas/pooja-3.jpg",
        tag: "White Marble",
        description: "Pure Makrana white marble altar with floating drawers for puja samagri and subtle floor washlights.",
      },
      {
        id: "pooja-4",
        title: "Gold Leaf Spiritual Sanctuary",
        image: "/images/design-ideas/pooja-4.jpg",
        tag: "Gold Leaf",
        description: "Gilded leaf accent niche creating an opulent, divine ambiance for daily meditation and prayers.",
      },
      {
        id: "pooja-5",
        title: "Jaali Screen Compact Pooja Unit",
        image: "/images/design-ideas/pooja-5.jpg",
        tag: "CNC Jaali",
        description: "Geometric CNC patterned sliding doors offering privacy and ventilation in modern apartments.",
      },
      {
        id: "pooja-6",
        title: "Warm Illuminated Divine Nook",
        image: "/images/design-ideas/pooja-6.jpg",
        tag: "Compact Nook",
        description: "Wall-mounted floating pooja unit with integrated diya drawers and warm focused spotlights.",
      },
    ],
  },
  {
    slug: "space-saving",
    name: "Space Saving",
    group: "Innovative Solutions",
    heroTitle: "Intelligent Space-Saving Designs That Double Your Living Area",
    heroSubtitle:
      "Maximize compact urban layouts with multifunctional convertible furniture, hidden storage, and clever folding mechanisms.",
    heroImage: "/images/design-ideas/spacesaving-hero.jpg",
    metaTitle: "Space Saving Interior Designs | The Bright Space Interiors",
    metaDescription:
      "Explore smart space-saving ideas including Murphy beds, hidden storage, modular furniture, and convertible tables.",
    designs: [
      {
        id: "space-1",
        title: "Foldable Murphy Bed & Desk",
        image: "/images/design-ideas/spacesaving-1.jpg",
        tag: "Convertible",
        description: "Seamless wall bed that folds away by day to reveal a full-width study workstation.",
      },
      {
        id: "space-2",
        title: "Multi-Functional Storage Ottoman Bench",
        image: "/images/design-ideas/spacesaving-2.jpg",
        tag: "Dual Function",
        description: "Living room upholstered window bench with hydraulic lid opening to generous linen storage.",
      },
      {
        id: "space-3",
        title: "Concealed Kitchen Appliance Garage",
        image: "/images/design-ideas/spacesaving-3.jpg",
        tag: "Hidden Storage",
        description: "Tambour roller door keeping small countertop appliances hidden yet instantly accessible.",
      },
      {
        id: "space-4",
        title: "Under-Bed Hydraulic Storage Lift",
        image: "/images/design-ideas/spacesaving-4.jpg",
        tag: "Heavy Storage",
        description: "Effortless gas-lift mattress mechanism revealing deep segmented storage for seasonal luggage.",
      },
      {
        id: "space-5",
        title: "Convertible Dining-to-Workstation",
        image: "/images/design-ideas/spacesaving-5.jpg",
        tag: "Multi-Use",
        description: "Extendable console table transforming from an entryway desk into an eight-seater dining table.",
      },
      {
        id: "space-6",
        title: "Nesting Modular Living Furniture",
        image: "/images/design-ideas/spacesaving-6.jpg",
        tag: "Modular",
        description: "Set of three graduated marble and oak coffee tables that slide together when space is needed.",
      },
    ],
  },
  {
    slug: "staircase",
    name: "Staircase",
    group: "Architectural Elements",
    heroTitle: "Architectural Staircase Designs That Make a Statement",
    heroSubtitle:
      "Elevate your home's multi-level circulation with floating cantilevered treads, sculptural railings, and ambient step lighting.",
    heroImage: "/images/design-ideas/staircase-hero.jpg",
    metaTitle: "Staircase Designs | The Bright Space Interiors",
    metaDescription:
      "Discover modern staircase designs with floating wooden treads, glass railings, spiral structures, and integrated step illumination.",
    designs: [
      {
        id: "stair-1",
        title: "Cantilevered Floating Wooden Stairs",
        image: "/images/design-ideas/staircase-1.jpg",
        tag: "Floating Treads",
        description: "Solid teak steps anchored directly into hidden steel wall stringers with recessed step LEDs.",
      },
      {
        id: "stair-2",
        title: "Glass Railing Contemporary Staircase",
        image: "/images/design-ideas/staircase-2.jpg",
        tag: "Frameless Glass",
        description: "Ultra-clear laminated glass balustrade creating uninterrupted light flow across both levels.",
      },
      {
        id: "stair-3",
        title: "Spiral Architectural Metal Steps",
        image: "/images/design-ideas/staircase-3.jpg",
        tag: "Spiral",
        description: "Sculptural curved helical staircase serving as a centerpiece art installation in double-height spaces.",
      },
      {
        id: "stair-4",
        title: "Marble Riser Grand Entry Stairway",
        image: "/images/design-ideas/staircase-4.jpg",
        tag: "Classic Grandeur",
        description: "Book-matched Italian marble treads complemented by bespoke cast brass decorative balusters.",
      },
      {
        id: "stair-5",
        title: "Integrated Under-Stair Display Shelving",
        image: "/images/design-ideas/staircase-5.jpg",
        tag: "Built-In Storage",
        description: "Custom geometric book niches and decorative artifact display integrated below the flight.",
      },
      {
        id: "stair-6",
        title: "Minimalist Black Steel Monorail Staircase",
        image: "/images/design-ideas/staircase-6.jpg",
        tag: "Industrial Chic",
        description: "Central spine steel structure supporting warm oak steps for a clean loft aesthetic.",
      },
    ],
  },
  {
    slug: "study-room",
    name: "Study Room",
    group: "Work & Study",
    heroTitle: "Focused Study Rooms and Executive Home Libraries",
    heroSubtitle:
      "Design quiet, productive study spaces equipped with custom bookshelves, ergonomic desks, and focused task lighting.",
    heroImage: "/images/design-ideas/study-hero.jpg",
    metaTitle: "Study Room Designs | The Bright Space Interiors",
    metaDescription:
      "Explore study room designs with custom bookshelves, floating workstations, reading nooks, and ergonomic setups.",
    designs: [
      {
        id: "study-1",
        title: "Quiet Executive Library & Study",
        image: "/images/design-ideas/study-1.jpg",
        tag: "Home Library",
        description: "Floor-to-ceiling dark wood library shelves with a rolling library ladder and leather reading chair.",
      },
      {
        id: "study-2",
        title: "Modern Minimalist Floating Desk",
        image: "/images/design-ideas/study-2.jpg",
        tag: "Minimalist",
        description: "Wall-mounted oak desk with concealed cable ducts and minimalist pin-board acoustic backer.",
      },
      {
        id: "study-3",
        title: "Dual-Workstation Family Study",
        image: "/images/design-ideas/study-3.jpg",
        tag: "Dual Station",
        description: "Side-by-side dedicated workstations separated by central drawer storage for shared productivity.",
      },
      {
        id: "study-4",
        title: "Cozy Window Nook Reading Bench",
        image: "/images/design-ideas/study-4.jpg",
        tag: "Window Nook",
        description: "Deep upholstered window bay seat flanked by built-in book cubbies and natural reading daylight.",
      },
      {
        id: "study-5",
        title: "Industrial Wall-Mounted Bookshelf Study",
        image: "/images/design-ideas/study-5.jpg",
        tag: "Industrial",
        description: "Modular steel pipe shelving framing an expansive walnut veneer desk and magnetic planner wall.",
      },
      {
        id: "study-6",
        title: "Ergonomic Focus & Study Corner",
        image: "/images/design-ideas/study-6.jpg",
        tag: "Compact Focus",
        description: "Acoustically insulated corner workstation with anti-glare overhead illumination and cable management.",
      },
    ],
  },
  {
    slug: "tv-unit",
    name: "TV Unit",
    group: "Living & Lounge",
    heroTitle: "Showstopper TV Units and Modern Media Walls",
    heroSubtitle:
      "Center your living space around a luxurious TV entertainment unit featuring fluted panels, marble backdrops, and floating consoles.",
    heroImage: "/images/design-ideas/tvunit-hero.jpg",
    metaTitle: "TV Unit Designs | The Bright Space Interiors",
    metaDescription:
      "Discover modern TV unit designs with fluted panelling, marble slabs, floating consoles, and hidden cable management.",
    designs: [
      {
        id: "tv-1",
        title: "Fluted Wood & Marble TV Wall",
        image: "/images/design-ideas/tvunit-1.jpg",
        tag: "Fluted Accent",
        description: "Sleek combination of warm timber fluted louvers alongside a central backlit Italian marble slab.",
      },
      {
        id: "tv-2",
        title: "Floating Minimalist Media Console",
        image: "/images/design-ideas/tvunit-2.jpg",
        tag: "Floating Console",
        description: "Suspended handleless low-board console with soft-close push drawers and under-glow LED lighting.",
      },
      {
        id: "tv-3",
        title: "Floor-to-Ceiling Display TV Unit",
        image: "/images/design-ideas/tvunit-3.jpg",
        tag: "Display Wall",
        description: "Full-wall entertainment unit with open glass display cubbies showcasing curated decor artifacts.",
      },
      {
        id: "tv-4",
        title: "Backlit Acoustic Slat Media Feature",
        image: "/images/design-ideas/tvunit-4.jpg",
        tag: "Acoustic Slats",
        description: "Sound-dampening dark oak acoustic felt slats framing an ultra-large screen with perimeter LEDs.",
      },
      {
        id: "tv-5",
        title: "Integrated Bookcase TV Frame",
        image: "/images/design-ideas/tvunit-5.jpg",
        tag: "Classic Library",
        description: "Symmetrical painted woodwork bookcase enclosing the screen seamlessly within traditional moldings.",
      },
      {
        id: "tv-6",
        title: "Rotating Partition Entertainment Unit",
        image: "/images/design-ideas/tvunit-6.jpg",
        tag: "360 Swivel",
        description: "Center pivot swivel unit allowing viewing from both the living lounge and dining space.",
      },
    ],
  },
  {
    slug: "wall-decor",
    name: "Wall Decor",
    group: "Finishes & Decor",
    heroTitle: "Curated Wall Decor and Architectural Panelling Features",
    heroSubtitle:
      "Transform plain walls into dimensional art with custom wood mouldings, mirror accents, metal installations, and fine art curations.",
    heroImage: "/images/design-ideas/walldecor-hero.jpg",
    metaTitle: "Wall Decor Designs | The Bright Space Interiors",
    metaDescription:
      "Explore creative wall decor ideas including fluted wall panels, metal art sculptures, bronze grid mirrors, and wainscoting.",
    designs: [
      {
        id: "decor-1",
        title: "Contemporary Abstract Metal Sculpture",
        image: "/images/design-ideas/walldecor-1.jpg",
        tag: "Metal Art",
        description: "Bespoke three-dimensional brass and iron geometric installation highlighted by focused ceiling pinspots.",
      },
      {
        id: "decor-2",
        title: "Fluted Wooden Wall Panelling Feature",
        image: "/images/design-ideas/walldecor-2.jpg",
        tag: "Timber Slats",
        description: "Warm vertical natural timber louvers creating texture, sound insulation, and architectural richness.",
      },
      {
        id: "decor-3",
        title: "Gallery Wall of Curated Fine Art",
        image: "/images/design-ideas/walldecor-3.jpg",
        tag: "Gallery Wall",
        description: "Custom brass-framed black-and-white architectural photography grouped with harmonious alignment.",
      },
      {
        id: "decor-4",
        title: "Bronze Tinted Mirror Grid Panelling",
        image: "/images/design-ideas/walldecor-4.jpg",
        tag: "Bronze Mirror",
        description: "Beveled bronze mirror panels multiplying room light and amplifying space in narrow living areas.",
      },
      {
        id: "decor-5",
        title: "3D Gypsum Geometric Wall Art",
        image: "/images/design-ideas/walldecor-5.jpg",
        tag: "3D Gypsum",
        description: "Textured modular gypsum wave panels finished with seamless matte paint and directional grazing light.",
      },
      {
        id: "decor-6",
        title: "Backlit Architectural Wood Slats",
        image: "/images/design-ideas/walldecor-6.jpg",
        tag: "Backlit Feature",
        description: "Concealed LED light channels washing down behind spaced wooden slats for evening mood ambiance.",
      },
    ],
  },
  {
    slug: "wall-paint",
    name: "Wall Paint",
    group: "Finishes & Decor",
    heroTitle: "Luxury Paint Finishes, Textures, and Color Palettes",
    heroSubtitle:
      "Define the mood of every room with artisan lime wash, Venetian stucco plaster, and curated designer color schemes.",
    heroImage: "/images/design-ideas/wallpaint-hero.jpg",
    metaTitle: "Wall Paint Designs & Finishes | The Bright Space Interiors",
    metaDescription:
      "Discover premium wall paint techniques including Italian stucco, textured limewash, accent color blocking, and metallic luster.",
    designs: [
      {
        id: "paint-1",
        title: "Venetian Stucco Marble Plaster",
        image: "/images/design-ideas/wallpaint-1.jpg",
        tag: "Venetian Stucco",
        description: "Troweled Italian lime plaster polished to a reflective, cool stone sheen with natural tonal depth.",
      },
      {
        id: "paint-2",
        title: "Limewash Matte Textured Finish",
        image: "/images/design-ideas/wallpaint-2.jpg",
        tag: "Limewash",
        description: "Breathable mineral limewash delivering chalky, soft cloud-like tonal movement across bedroom walls.",
      },
      {
        id: "paint-3",
        title: "Dual-Tone Warm Neutral Palette",
        image: "/images/design-ideas/wallpaint-3.jpg",
        tag: "Color Block",
        description: "Subtle split horizontal color zoning pairing warm oatmeal with soft creamy ivory for height emphasis.",
      },
      {
        id: "paint-4",
        title: "Moody Charcoal & Gold Leaf Accent",
        image: "/images/design-ideas/wallpaint-4.jpg",
        tag: "Dramatic",
        description: "Deep matte charcoal accent wall detailed with hand-applied distressed gold leaf flecks.",
      },
      {
        id: "paint-5",
        title: "Sage Green Serenity Bedroom Wash",
        image: "/images/design-ideas/wallpaint-5.jpg",
        tag: "Earthy Green",
        description: "Restorative botanical sage hue that softens bedroom daylight and promotes deep restful sleep.",
      },
      {
        id: "paint-6",
        title: "Metallic Pearl Luster Finish",
        image: "/images/design-ideas/wallpaint-6.jpg",
        tag: "Metallic Luster",
        description: "Micro-fine pearlescent glaze catching shifting ambient angles in foyer entryways.",
      },
    ],
  },
  {
    slug: "window",
    name: "Window",
    group: "Architectural Elements",
    heroTitle: "Window Treatments, Casements, and Natural Light Framing",
    heroSubtitle:
      "Frame outdoor vistas and control natural light with floor-to-ceiling picture glass, custom draperies, and architectural frames.",
    heroImage: "/images/design-ideas/window-hero.jpg",
    metaTitle: "Window Designs & Treatments | The Bright Space Interiors",
    metaDescription:
      "Explore modern window ideas with floor-to-ceiling glass, black aluminium casements, bay window seating, and motorized drapes.",
    designs: [
      {
        id: "win-1",
        title: "Floor-to-Ceiling Picture Glass Window",
        image: "/images/design-ideas/window-1.jpg",
        tag: "Panoramic",
        description: "Minimalist thermal-break framing connecting living spaces seamlessly with surrounding garden landscapes.",
      },
      {
        id: "win-2",
        title: "Modern Black Aluminium Casement Window",
        image: "/images/design-ideas/window-2.jpg",
        tag: "Industrial Modern",
        description: "Narrow-sightline powder coated black frames introducing crisp architectural definition.",
      },
      {
        id: "win-3",
        title: "Bay Window with Cozy Cushioned Seat",
        image: "/images/design-ideas/window-3.jpg",
        tag: "Bay Window",
        description: "Deep panoramic bay window with integrated drawers and custom tufted cushions for afternoon reading.",
      },
      {
        id: "win-4",
        title: "Motorized Sheer & Blackout Drapes",
        image: "/images/design-ideas/window-4.jpg",
        tag: "Smart Drapery",
        description: "Recessed ceiling track motorized curtains combining billowy linen sheers with 100% blackout liners.",
      },
      {
        id: "win-5",
        title: "French Glass Windows with Garden Views",
        image: "/images/design-ideas/window-5.jpg",
        tag: "French Classic",
        description: "Double-hinged white colonial French doors opening outwards to private balcony gardens.",
      },
      {
        id: "win-6",
        title: "Arched Heritage Wooden Shutter Window",
        image: "/images/design-ideas/window-6.jpg",
        tag: "Arched Heritage",
        description: "Custom louvred plantation shutters set within an elegant architectural semicircular arch.",
      },
    ],
  },
  {
    slug: "tile",
    name: "Tile",
    group: "Finishes & Decor",
    heroTitle: "Designer Tiles, Marble Slabs, and Artisanal Mosaics",
    heroSubtitle:
      "Set the foundation of exquisite interiors with large-format porcelain slabs, handcrafted Moroccan zellige, and geometric mosaics.",
    heroImage: "/images/design-ideas/tile-hero.jpg",
    metaTitle: "Tile Designs & Patterns | The Bright Space Interiors",
    metaDescription:
      "Discover stunning tile design concepts including large-format porcelain, herringbone backsplashes, terrazzo floors, and mosaics.",
    designs: [
      {
        id: "tile-1",
        title: "Large-Format Italian Porcelain Slab",
        image: "/images/design-ideas/tile-1.jpg",
        tag: "Porcelain Slab",
        description: "Continuous book-matched Statuario marble porcelain tiles minimizing grout lines across living floors.",
      },
      {
        id: "tile-2",
        title: "Moroccan Encaustic Handcrafted Tile",
        image: "/images/design-ideas/tile-2.jpg",
        tag: "Encaustic",
        description: "Artisan cement tiles featuring intricate heritage Mediterranean star patterns in foyer entries.",
      },
      {
        id: "tile-3",
        title: "Herringbone White Subway Kitchen Backsplash",
        image: "/images/design-ideas/tile-3.jpg",
        tag: "Herringbone",
        description: "Handmade ceramic subway tiles laid in a dynamic 45-degree herringbone pattern with contrasting grout.",
      },
      {
        id: "tile-4",
        title: "Terrazzo Fleck Modern Bathroom Floor",
        image: "/images/design-ideas/tile-4.jpg",
        tag: "Terrazzo",
        description: "Polished composite terrazzo tile incorporating colorful quartz chips and brass transition joints.",
      },
      {
        id: "tile-5",
        title: "Hexagonal Geometric Mosaic Tiles",
        image: "/images/design-ideas/tile-5.jpg",
        tag: "Hexagon Mosaic",
        description: "Matte black and white hexagonal ceramic sheets transitioning organically into hardwood boards.",
      },
      {
        id: "tile-6",
        title: "Wood-Look Porcelain Plank Flooring",
        image: "/images/design-ideas/tile-6.jpg",
        tag: "Wood Plank",
        description: "Textured oak-embossed porcelain planks delivering natural warmth with zero moisture maintenance.",
      },
    ],
  },
  {
    slug: "front-elevation",
    name: "Front Elevation",
    group: "Architectural Elements",
    heroTitle: "Stunning Front Elevation and Facade Architecture",
    heroSubtitle:
      "Create unforgettable exterior curb appeal with modern architectural massing, kinetic louvers, stone cladding, and facade illumination.",
    heroImage: "/images/design-ideas/elevation-hero.jpg",
    metaTitle: "Front Elevation Designs | The Bright Space Interiors",
    metaDescription:
      "Explore modern residential front elevation designs, villa facades, architectural cladding, and dramatic exterior lighting.",
    designs: [
      {
        id: "elevation-1",
        title: "Modern Contemporary Villa Facade",
        image: "/images/design-ideas/elevation-1.jpg",
        tag: "Modern Villa",
        description: "Geometric cantilevered box volumes, tinted glass balconies, and warm wood louvers.",
      },
      {
        id: "elevation-2",
        title: "Brutalist Concrete & Teak Wood Elevation",
        image: "/images/design-ideas/elevation-2.jpg",
        tag: "Board-Form Concrete",
        description: "Exposed textured board-form concrete offset by rich oiled Burmese teak slats and vertical planters.",
      },
      {
        id: "elevation-3",
        title: "Classical Neoclassical Arched Villa",
        image: "/images/design-ideas/elevation-3.jpg",
        tag: "Neoclassical",
        description: "Symmetrical arched windows, molded cornices, and grand double-height entrance columns.",
      },
      {
        id: "elevation-4",
        title: "Minimalist Glass & Steel Residential Front",
        image: "/images/design-ideas/elevation-4.jpg",
        tag: "Glass & Steel",
        description: "Black steel structural frames with expansive triple-glazed reflective low-E glass facade panels.",
      },
      {
        id: "elevation-5",
        title: "Louvered Kinetic Screen Facade",
        image: "/images/design-ideas/elevation-5.jpg",
        tag: "Motorized Louvers",
        description: "Perforated metal screening that pivots to adapt to changing sunlight angles while ensuring privacy.",
      },
      {
        id: "elevation-6",
        title: "Stone Cladding & Warm Exterior Illumination",
        image: "/images/design-ideas/elevation-6.jpg",
        tag: "Stone Cladding",
        description: "Natural dry-stacked slate stone walls accentuated by upward warm LED architectural grazers.",
      },
    ],
  },
  {
    slug: "kitchen-interiors",
    name: "Kitchen Interiors",
    group: "Kitchen & Dining",
    heroTitle: "Inspiring Kitchen Interiors Tailored for Every Chef",
    heroSubtitle:
      "Transform your kitchen into a luxurious culinary paradise with quartz surfaces, smart appliance towers, and bespoke cabinetry.",
    heroImage: "/images/design-ideas/kitcheninteriors-hero.jpg",
    metaTitle: "Kitchen Interior Designs | The Bright Space Interiors",
    metaDescription:
      "Discover kitchen interior ideas featuring handleless acrylic cabinets, island breakfast counters, and pantry tall-units.",
    designs: [
      {
        id: "kint-1",
        title: "High-Gloss Acrylic Handleless Kitchen",
        image: "/images/design-ideas/kitcheninteriors-1.jpg",
        tag: "High Gloss",
        description: "Ultra-reflective glass-finish acrylic shutters with aluminum Gola profile finger grooves.",
      },
      {
        id: "kint-2",
        title: "Chef's Island with Waterfall Quartz",
        image: "/images/design-ideas/kitcheninteriors-2.jpg",
        tag: "Island Bar",
        description: "Calacatta gold quartz surface cascading down both island sides with embedded barstool seating.",
      },
      {
        id: "kint-3",
        title: "Country Cottage Shaker Kitchen",
        image: "/images/design-ideas/kitcheninteriors-3.jpg",
        tag: "Shaker Classic",
        description: "Muted duck-egg blue framed shaker cabinetry with solid brass cup pull hardware and ceramic apron sink.",
      },
      {
        id: "kint-4",
        title: "Matte Black & Brass Culinary Haven",
        image: "/images/design-ideas/kitcheninteriors-4.jpg",
        tag: "Moody Chic",
        description: "Anti-fingerprint thermal matte black cabinetry with brushed champagne brass accents and smoked splashback.",
      },
      {
        id: "kint-5",
        title: "Open-Plan Breakfast Bar Kitchen",
        image: "/images/design-ideas/kitcheninteriors-5.jpg",
        tag: "Open Plan",
        description: "Seamless open flow connecting the cooking zone with living areas across a casual dining breakfast peninsula.",
      },
      {
        id: "kint-6",
        title: "Compact U-Shaped Urban Kitchen",
        image: "/images/design-ideas/kitcheninteriors-6.jpg",
        tag: "U-Shaped",
        description: "Optimized golden work triangle with corner carousel pullouts and tall spice storage racks.",
      },
    ],
  },
  {
    slug: "kids-bedroom-designs",
    name: "Kids Bedroom Designs",
    group: "Bedrooms & Suites",
    heroTitle: "Imaginative, Functional, and Safe Spaces for Children",
    heroSubtitle:
      "Design cheerful bedrooms that grow with your children, featuring smart bunk beds, interactive study zones, and durable finishes.",
    heroImage: "/images/design-ideas/kids-hero.jpg",
    metaTitle: "Kids Bedroom Designs | The Bright Space Interiors",
    metaDescription:
      "Explore creative kids bedroom designs with custom bunk beds, study corners, pastel themes, and safe rounded storage.",
    designs: [
      {
        id: "kids-1",
        title: "Playful Bunk Bed with Built-In Storage",
        image: "/images/design-ideas/kids-1.jpg",
        tag: "Bunk Bed",
        description: "Custom timber double bunk with stairs featuring integrated toy drawers and safety guardrails.",
      },
      {
        id: "kids-2",
        title: "Montessori Pastel Adventure Bedroom",
        image: "/images/design-ideas/kids-2.jpg",
        tag: "Montessori",
        description: "Low-profile floor bed with accessible open shelving promoting child independence and calm play.",
      },
      {
        id: "kids-3",
        title: "Starry Sky Themed Study & Sleep Suite",
        image: "/images/design-ideas/kids-3.jpg",
        tag: "Theme Suite",
        description: "Fiber-optic constellation ceiling canopy above an ergonomic study desk and cozy sleeping pod.",
      },
      {
        id: "kids-4",
        title: "Vibrant Creative Activity Kids Room",
        image: "/images/design-ideas/kids-4.jpg",
        tag: "Creative Play",
        description: "Magnetic chalk activity accent wall with colorful cubbies and washable hypoallergenic finishes.",
      },
      {
        id: "kids-5",
        title: "Twin Bed Scandinavian Nursery",
        image: "/images/design-ideas/kids-5.jpg",
        tag: "Scandinavian",
        description: "Natural pine timber frames paired with gender-neutral muted olive and warm grey tones.",
      },
      {
        id: "kids-6",
        title: "Teenager Lofty Loft Bed Studio",
        image: "/images/design-ideas/kids-6.jpg",
        tag: "Teen Loft",
        description: "Elevated loft bed freeing the entire floor below for a modern gaming and study lounge.",
      },
    ],
  },
  {
    slug: "foyer-designs",
    name: "Foyer Designs",
    group: "Living & Lounge",
    heroTitle: "Memorable Entryway Foyers That Set a Welcoming Tone",
    heroSubtitle:
      "Craft a breathtaking first impression with artistic console tables, sunburst mirrors, smart shoe cabinetry, and statement lighting.",
    heroImage: "/images/design-ideas/foyer-hero.jpg",
    metaTitle: "Foyer & Entryway Designs | The Bright Space Interiors",
    metaDescription:
      "Discover entryway foyer designs featuring console tables, statement mirrors, shoe storage benches, and warm welcoming lighting.",
    designs: [
      {
        id: "foyer-1",
        title: "Grand Entryway with Console & Sunburst Mirror",
        image: "/images/design-ideas/foyer-1.jpg",
        tag: "Grand Arrival",
        description: "Fluted marble console table centered below a dramatic gilded sunburst mirror and sculptural floral vase.",
      },
      {
        id: "foyer-2",
        title: "Modern Partition Wall with Ambient Sconces",
        image: "/images/design-ideas/foyer-2.jpg",
        tag: "Partition Wall",
        description: "Bronze metal and fluted glass architectural divider separating the foyer from the main living room.",
      },
      {
        id: "foyer-3",
        title: "Compact Shoe Storage & Bench Nook",
        image: "/images/design-ideas/foyer-3.jpg",
        tag: "Smart Entry",
        description: "Concealed push-open shoe cabinetry with integrated seat cushion and coat hanging niche.",
      },
      {
        id: "foyer-4",
        title: "Statement Marble Flooring Arrival Hall",
        image: "/images/design-ideas/foyer-4.jpg",
        tag: "Marble Inlay",
        description: "Geometric water-jet marble medallion floor medallion illuminated by a warm crystal chandelier drop.",
      },
      {
        id: "foyer-5",
        title: "Backlit Onyx Feature Wall Entryway",
        image: "/images/design-ideas/foyer-5.jpg",
        tag: "Backlit Onyx",
        description: "Luminous natural stone feature wall greeting guests with an ethereal amber glow.",
      },
      {
        id: "foyer-6",
        title: "Art Gallery Corridor Foyer",
        image: "/images/design-ideas/foyer-6.jpg",
        tag: "Art Gallery",
        description: "Linear spotlight ceiling track illuminating curated framed paintings along the arrival passage.",
      },
    ],
  },
  {
    slug: "dressing-room-designs",
    name: "Dressing Room Designs",
    group: "Bedrooms & Suites",
    heroTitle: "Boutique Dressing Rooms and Glamorous Walk-In Closets",
    heroSubtitle:
      "Experience the pinnacle of luxury dressing with custom accessory islands, illuminated vanity mirrors, and velvet seating.",
    heroImage: "/images/design-ideas/dressing-hero.jpg",
    metaTitle: "Dressing Room Designs | The Bright Space Interiors",
    metaDescription:
      "Explore bespoke dressing room designs with central jewelry islands, lighted vanities, glass wardrobes, and boutique organization.",
    designs: [
      {
        id: "dressing-1",
        title: "Luxury Walk-In Boutique Dressing Room",
        image: "/images/design-ideas/dressing-1.jpg",
        tag: "Boutique Luxury",
        description: "Floor-to-ceiling illuminated open wardrobe bays with dedicated handbag displays and velvet drawers.",
      },
      {
        id: "dressing-2",
        title: "Central Glass Island with Watch & Jewelry Drawers",
        image: "/images/design-ideas/dressing-2.jpg",
        tag: "Center Island",
        description: "Tempered glass top island showcase with velvet dividers for watches, jewelry, and accessories.",
      },
      {
        id: "dressing-3",
        title: "Backlit Full-Length Glamour Vanity",
        image: "/images/design-ideas/dressing-3.jpg",
        tag: "Glamour Vanity",
        description: "Dedicated dressing vanity with shadowless daylight 4000K bulb framing and velvet swivel chair.",
      },
      {
        id: "dressing-4",
        title: "Minimalist Sliding Mirror Wardrobe Suite",
        image: "/images/design-ideas/dressing-4.jpg",
        tag: "Full Mirror",
        description: "Full-height tinted mirrors expanding space perceptions while providing head-to-toe styling views.",
      },
      {
        id: "dressing-5",
        title: "Velvet Ottoman Boudoir Dressing Area",
        image: "/images/design-ideas/dressing-5.jpg",
        tag: "Boudoir Elegance",
        description: "Tufted circular center ottoman in champagne velvet anchoring a tranquil, carpeted dressing haven.",
      },
      {
        id: "dressing-6",
        title: "Compact Master Bedroom Dressing Nook",
        image: "/images/design-ideas/dressing-6.jpg",
        tag: "Compact Nook",
        description: "Clever corner dressing solution featuring vertical pullout mirrors and integrated cosmetic organizers.",
      },
    ],
  },
];

export function getAllDesignCategories(): DesignCategory[] {
  return DESIGN_CATEGORIES;
}

export function getDesignCategoryBySlug(slug: string): DesignCategory | undefined {
  return DESIGN_CATEGORIES.find((cat) => cat.slug === slug);
}

export const CATEGORY_GROUPS = [
  "All",
  "Dining & Storage",
  "Kitchen & Dining",
  "Bedrooms & Suites",
  "Living & Lounge",
  "Baths & Wellness",
  "Work & Study",
  "Commercial & Hospitality",
  "Commercial & Specialized",
  "Spiritual & Traditional",
  "Architectural Elements",
  "Finishes & Decor",
  "Innovative Solutions",
  "Outdoor & Extended",
];
